CREATE TABLE request_categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(30) NOT NULL,
    name        VARCHAR(80) NOT NULL,
    active      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_request_categories_code UNIQUE (code),
    CONSTRAINT uk_request_categories_name UNIQUE (name),
    CONSTRAINT ck_request_categories_code_not_blank CHECK (length(trim(code)) > 0),
    CONSTRAINT ck_request_categories_name_not_blank CHECK (length(trim(name)) > 0)
);

COMMENT ON TABLE request_categories IS 'Categorias disponíveis para classificar solicitações';
