CREATE TABLE requests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR(150) NOT NULL,
    description     TEXT NOT NULL,
    category_id     BIGINT NOT NULL,
    requester_id    BIGINT NOT NULL,
    status          VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_requests_category FOREIGN KEY (category_id)
        REFERENCES request_categories (id),
    CONSTRAINT fk_requests_requester FOREIGN KEY (requester_id)
        REFERENCES users (id),
    CONSTRAINT ck_requests_title_not_blank CHECK (length(trim(title)) > 0),
    CONSTRAINT ck_requests_description_not_blank CHECK (length(trim(description)) > 0),
    CONSTRAINT ck_requests_status CHECK (status IN ('OPEN', 'IN_PROGRESS', 'COMPLETED'))
);

COMMENT ON TABLE requests IS 'Solicitações internas registradas pelos colaboradores';
COMMENT ON COLUMN requests.status IS 'OPEN, IN_PROGRESS ou COMPLETED';

CREATE INDEX idx_requests_requester_id ON requests (requester_id);
CREATE INDEX idx_requests_category_id ON requests (category_id);
CREATE INDEX idx_requests_status ON requests (status);
CREATE INDEX idx_requests_created_at ON requests (created_at);
